permalink:           pretty

# Setup
title:               HomeIO
tagline:             'an universal system for remote monitor and control'
description:         "HomeIO is free, open source, universal system for remote monitor and control of various systems."
url:                 http://homeio.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Aleksander Kwiatkowski
  url:               https://github.com/akwiatkowski
  email:             homeio@interia.eu

# Custom vars
version:             0.2.0

# Jekyll internals
gems:
- jekyll-paginate
- jekyll-sitemap

twitter_username: bobik314
github_username:  akwiatkowski

github: https://github.com/HomeIO/
github_firmware: "https://github.com/HomeIO/homeio_firmware_arduino"
